source 'https://rubygems.org'

gem 'rails', '3.2.22'
gem 'pg'
gem 'test-unit'

gem 'authlogic'
gem 'scrypt'

gem 'json'
gem 'yajl-ruby' # apparently necessary to parse JSON post data
gem 'rabl'

# Gems used only for assets and not required
# in production environments by default.
#group :assets do  
  #gem 'therubyracer'
  #gem 'less-rails'
#  gem 'twitter-bootstrap-rails', github: 'seyhunak/twitter-bootstrap-rails', branch: 'bootstrap3'
#end

gem 'bootstrap-sass', '~> 3.1.1.0'
gem 'sass-rails', '>= 3.2'
gem 'uglifier'

gem 'jquery-rails'

# Image Uploads
gem 'carrierwave'
gem 'rmagick', :require => 'rmagick'

# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano'
gem 'capistrano-rvm'
gem 'capistrano-bundler'
gem 'capistrano-rails'

# To use debugger
# gem 'debugger'
